CREATE TABLE IF NOT EXISTS Clienti (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(255) NOT NULL,
    Cognome VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Telefono VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS Aquisti (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT,
    ClienteID INTEGER NOT NULL,
    Prodotto VARCHAR(255) NOT NULL,
    Prezzo REAL NOT NULL,
    DataAcquisto DATE NOT NULL,
    FOREIGN KEY (ClienteID) REFERENCES Clienti(ID) ON DELETE CASCADE
);